import { formatGuardianNumber } from "@/lib/certificates/certificate-format";
import { emailShell, escapeHtml, type TransactionalEmail } from "@/lib/email/templates/shared";

export function approvalCertificateEmail(displayName: string, guardianNumber: number): TransactionalEmail {
  const name = displayName.trim();
  const number = formatGuardianNumber(guardianNumber);
  return {
    subject: "Mirchi Vriksha Bandhan Certificate",
    templateVersion: "approval-certificate-v4",
    html: emailShell("Your Vriksha Guardian certificate is attached", `<p style="margin:0 0 18px;color:#d92d2f;font-size:12px;line-height:18px;font-weight:700;letter-spacing:1.6px;text-transform:uppercase">Submission approved</p><h1 style="margin:0 0 18px;color:#193d32;font-family:Georgia,'Times New Roman',serif;font-size:34px;line-height:42px;font-weight:700">A bond worth celebrating.</h1><p style="margin:0 0 22px;color:#344f46;font-size:16px;line-height:26px">Dear ${escapeHtml(name)},</p><p style="margin:0 0 26px;color:#344f46;font-size:16px;line-height:26px">Your photograph has been approved and is now part of Vriksha Bandhan. Thank you for turning gratitude into a living promise.</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;margin:0 0 26px;background:#f5f1e6;border:1px solid #d8cfb7"><tr><td style="padding:22px 24px"><p style="margin:0 0 6px;color:#826f3a;font-size:11px;line-height:16px;font-weight:700;letter-spacing:1.5px;text-transform:uppercase">Your recognition</p><p style="margin:0;color:#193d32;font-family:Georgia,'Times New Roman',serif;font-size:25px;line-height:34px;font-weight:700">Vriksha Guardian No. ${number}</p></td></tr></table><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;margin:0 0 18px;border-left:4px solid #d92d2f;background:#fffaf2"><tr><td style="padding:16px 18px"><p style="margin:0 0 4px;color:#193d32;font-size:14px;line-height:21px;font-weight:700">Your certificate is attached</p><p style="margin:0;color:#596d65;font-size:13px;line-height:20px">Open the PDF attached to this email to view, save, or print your personalized certificate.</p></td></tr></table><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;margin:0 0 26px;border-left:4px solid #193d32;background:#f2f7f4"><tr><td style="padding:16px 18px"><p style="margin:0 0 4px;color:#193d32;font-size:14px;line-height:21px;font-weight:700">Share your moment</p><p style="margin:0;color:#596d65;font-size:13px;line-height:20px">If you share your Vriksha Bandhan moment on social media, please tag <strong style="color:#193d32">@MirchiMumbai</strong> so we can celebrate it with you.</p></td></tr></table><p style="margin:0;color:#344f46;font-size:16px;line-height:26px">With gratitude,<br><strong>The Mirchi Vriksha Bandhan Team</strong></p>`),
    text: `Dear ${name},\n\nYour photograph has been approved and is now part of Vriksha Bandhan. Thank you for turning gratitude into a living promise.\n\nYour recognition: Vriksha Guardian No. ${number}\n\nYour personalized certificate is attached to this email as a PDF. Open the attachment to view, save, or print it.\n\nIf you share your Vriksha Bandhan moment on social media, please tag @MirchiMumbai so we can celebrate it with you.\n\nWith gratitude,\nThe Mirchi Vriksha Bandhan Team\n\n983 Trees. One Frequency. Infinite Gratitude.`,
  };
}
