import { emailShell, escapeHtml, type TransactionalEmail } from "@/lib/email/templates/shared";

export function rejectionEmail(displayName: string): TransactionalEmail {
  const name = displayName.trim();
  return {
    subject: "Please submit your Vriksha Bandhan photograph again",
    templateVersion: "rejection-v4",
    html: emailShell("Please submit your Vriksha Bandhan photograph again", `<p style="margin:0 0 18px;color:#d92d2f;font-size:12px;line-height:18px;font-weight:700;letter-spacing:1.6px;text-transform:uppercase">Your submission needs another try</p><h1 style="margin:0 0 18px;color:#193d32;font-family:Georgia,'Times New Roman',serif;font-size:34px;line-height:42px;font-weight:700">Your Vriksha Bandhan journey can continue.</h1><p style="margin:0 0 22px;color:#344f46;font-size:16px;line-height:26px">Dear ${escapeHtml(name)},</p><p style="margin:0 0 24px;color:#344f46;font-size:16px;line-height:26px">Thank you for sharing your Vriksha Bandhan moment.</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;margin:0 0 18px;border-left:4px solid #d92d2f;background:#fffaf2"><tr><td style="padding:17px 18px"><p style="margin:0 0 5px;color:#193d32;font-size:14px;line-height:21px;font-weight:700">We could not approve your photograph this time</p><p style="margin:0;color:#596d65;font-size:14px;line-height:22px">This may be because the photograph was unclear, the tree or Rakhi was not clearly visible, or it did not meet the campaign guidelines.</p></td></tr></table><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;margin:0 0 24px;border-left:4px solid #193d32;background:#f2f7f4"><tr><td style="padding:17px 18px"><p style="margin:0 0 5px;color:#193d32;font-size:14px;line-height:21px;font-weight:700">Please submit once again</p><p style="margin:0;color:#596d65;font-size:14px;line-height:22px">Please submit a new, well-lit photograph that clearly shows the Rakhi tied to the tree. We would be happy to review it again.</p></td></tr></table><p style="margin:0;color:#344f46;font-size:16px;line-height:26px">With gratitude,<br><strong>The Mirchi Vriksha Bandhan Team</strong></p>`),
    text: `Dear ${name},\n\nThank you for sharing your Vriksha Bandhan moment.\n\nWe could not approve your photograph this time. This may be because the photograph was unclear, the tree or Rakhi was not clearly visible, or it did not meet the campaign guidelines.\n\nPlease submit a new, well-lit photograph that clearly shows the Rakhi tied to the tree. We would be happy to review it again.\n\nWith gratitude,\nThe Mirchi Vriksha Bandhan Team\n\n983 Trees. One Frequency. Infinite Gratitude.`,
  };
}
